SLURM_MEM_PER_CPU=8192
SLURM_NODEID=0
SLURM_TASK_PID=177324
SLURM_PRIO_PROCESS=0
SLURM_SUBMIT_DIR=/users/ibarbier/AC-DC
SLURM_CPUS_PER_TASK=40
SLURM_PROCID=0
SLURM_JOB_GID=11000
SLURMD_NODENAME=dna037
SLURM_TASKS_PER_NODE=1
SLURM_NNODES=1
SLURM_JOB_NODELIST=dna037
SLURM_CLUSTER_NAME=curnagl
SLURM_NODELIST=dna037
SLURM_NTASKS=1
SLURM_JOB_CPUS_PER_NODE=40
SLURM_TOPOLOGY_ADDR=core.edge2.dna037
SLURM_WORKING_CLUSTER=curnagl:admin1:6817:9216:109
SLURM_JOB_NAME=sbatch_icvara.sh
SLURM_JOBID=547274
SLURM_CONF=/etc/slurm/slurm.conf
SLURM_NODE_ALIASES=(null)
SLURM_JOB_QOS=cpu-normal
SLURM_TOPOLOGY_ADDR_PATTERN=switch.switch.node
SLURM_CPUS_ON_NODE=40
SLURM_JOB_NUM_NODES=1
SLURM_JOB_UID=69294
SLURM_JOB_PARTITION=cpu
SLURM_JOB_USER=ibarbier
SLURM_NPROCS=1
SLURM_SUBMIT_HOST=login.curnagl
SLURM_JOB_ACCOUNT=yschaerl_snsf_2017
SLURM_GTIDS=0
SLURM_JOB_ID=547274
SLURM_LOCALID=0
SMC step with target distance: 200.0
>>>> Loop processing time: 5.376 sec on 40 CPU cores.
acceptance rate: 0.949667616334283
min accepted distance:  12.000000000338382
median accepted distance:  12.000053128695846
median evaluated distance:  12.000086240321533
SMC step with target distance: 12.000053128695846
>>>> Loop processing time: 580.859 sec on 40 CPU cores.
acceptance rate: 0.4734848484848485
min accepted distance:  12.0000000002721
median accepted distance:  12.00000003035775
median evaluated distance:  12.000083805385154
SMC step with target distance: 12.00000003035775
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "abc_smc.py", line 86, in GeneratePar
    d = model_equation.distance(x_data,p)
  File "/users/ibarbier/AC-DC/model_equation.py", line 124, in distance
    d2=abs(((maxValues[-1]-minValues[-1]) - (maxValues[0]-minValues[0]))/(maxValues[-1]-minValues[-1])) #stability of oscillation first and last peaks
IndexError: index -1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "abc_smc.py", line 236, in <module>
    main(sys.argv[1:])
  File "abc_smc.py", line 233, in main
    Sequential_ABC(x_data, ncpus=40,initial_dist = 200.0, final_dist =2.0,prior_label = None,Npars=1000)
  File "abc_smc.py", line 204, in Sequential_ABC
    Npars = Npars, kernelfactor = kernelfactor)
  File "abc_smc.py", line 139, in GeneratePars
    iterable=range(Npars), chunksize=10)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: index -1 is out of bounds for axis 0 with size 0
